# Generated by Django 5.0.2 on 2024-03-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profilelink_remove_userprofile_category_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelink',
            name='friendly_name',
        ),
    ]
