# Generated by Django 5.0.2 on 2024-03-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_category_name_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelink',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
