# Generated by Django 5.0.2 on 2024-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profilelink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
