# Generated by Django 5.0.2 on 2024-05-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
    ]
