# Generated by Django 5.0.2 on 2024-05-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_userprofile_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelink',
            old_name='link',
            new_name='url',
        ),
    ]
