# Generated by Django 5.0.2 on 2024-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rename_link_profilelink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_states',
            field=models.ManyToManyField(blank=True, to='profiles.teachingstate'),
        ),
    ]
