# Generated by Django 5.0.2 on 2024-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_teachingstate_userprofile_teaching_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_password_changed',
            field=models.BooleanField(default=True),
        ),
    ]
