# Generated by Django 5.0.2 on 2024-05-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_userprofile_is_password_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_password_changed',
            new_name='is_password_set',
        ),
    ]
