# Generated by Django 5.0.2 on 2024-05-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_rename_is_password_changed_userprofile_is_password_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_password_set',
            new_name='is_password_change',
        ),
    ]
