# Generated by Django 5.0.2 on 2024-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_rename_is_password_change_userprofile_is_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=501, null=True),
        ),
    ]
