# Generated by Django 5.0.2 on 2024-02-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_folder_event_friendly_name_alter_event_date_and_more'),
        ('resources', '0005_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.folder'),
        ),
    ]
