# Generated by Django 5.0.2 on 2024-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
