# Generated by Django 5.0.2 on 2024-05-21 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_registration_link'),
        ('resources', '0006_remove_resource_resource_type_remove_folder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='event',
            name='google_drive_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_drive_link', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='event',
            name='register_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_link', to='resources.resource'),
        ),
    ]
