# Generated by Django 5.0.2 on 2024-05-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_duration'),
        ('resources', '0007_resourcetype_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_drive_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_google_drive_link', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_register_link', to='resources.resource'),
        ),
    ]
