# Generated by Django 5.0.2 on 2024-02-13 04:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=27.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='membership',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershippackage'),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipstatus'),
        ),
    ]
