# Generated by Django 5.0.2 on 2024-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershippackage_membershipstatus_membership_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstatus',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
