# Generated by Django 5.0.2 on 2024-02-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membershipstatus_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='membershippackage',
            name='duration',
            field=models.IntegerField(verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='membershippackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=10, verbose_name='Price ($USD)'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validity'),
        ),
    ]
