# Generated by Django 5.0.2 on 2024-02-13 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_membership_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
