# Generated by Django 5.0.2 on 2024-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_membership_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='friendly_name',
            field=models.CharField(default='Yearly Membership', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipstatus',
            name='friendly_name',
            field=models.CharField(default='Active', max_length=254),
            preserve_default=False,
        ),
    ]
