# Generated by Django 5.0.2 on 2024-02-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_membershippackage_friendly_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='description',
            field=models.TextField(default='This membership costs $27.00, and it is valid for 365 days'),
            preserve_default=False,
        ),
    ]
