# Generated by Django 5.0.2 on 2024-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_membershippackage_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
