# Generated by Django 5.0.2 on 2024-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_alter_membershippackage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status_name',
            field=models.CharField(default='active', max_length=254),
            preserve_default=False,
        ),
    ]
