# Generated by Django 5.0.2 on 2024-02-21 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_alter_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
