# Generated by Django 5.0.2 on 2024-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_alter_membership_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('last_updated_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
