# Generated by Django 5.0.2 on 2024-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_membershipupdatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipupdatestatus',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
