# Generated by Django 5.0.2 on 2024-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_membershipupdatestatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipupdatestatus',
            name='friendly_name',
            field=models.CharField(default='membership_update_status', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipupdatestatus',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
