# Generated by Django 5.0.2 on 2024-02-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_alter_membershipupdatestatus_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipupdatestatus',
            name='friendly_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='membershipupdatestatus',
            name='name',
            field=models.CharField(editable=False, max_length=254, unique=True),
        ),
    ]
