# Generated by Django 5.0.2 on 2024-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_alter_membershipupdatestatus_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipupdatestatus',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
