# Generated by Django 5.0.2 on 2024-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_alter_membershipupdatestatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstatus',
            name='color',
            field=models.CharField(blank=True, default='success', max_length=254, null=True),
        ),
    ]
