# Generated by Django 5.0.2 on 2024-04-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0024_membershipstatus_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
