# Generated by Django 5.0.2 on 2024-04-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_alter_membership_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_valid',
        ),
    ]
