# Generated by Django 5.0.2 on 2024-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0026_remove_membership_cost_remove_membership_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippackage',
            name='checkout_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
