# Generated by Django 5.0.2 on 2024-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_alter_membershippackage_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipupdatestatus',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
