# Generated by Django 5.0.6 on 2024-06-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_awaiting_approval',
            field=models.BooleanField(default=True),
        ),
    ]
