# Generated by Django 3.2 on 2023-08-27 10:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=255)),
                ('member_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('member_short_uuid', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default='True')),
                ('is_superuser', models.BooleanField(default='False')),
                ('is_staff', models.BooleanField(default='False')),
                ('is_member', models.BooleanField(default='False')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', main_app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('event_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dikcjjfpo/image/upload/v1692796802/mreea-meeting-2_oeygy7.png', max_length=255, null=True, verbose_name='Event Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_short_uuid', models.CharField(default='', editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Other', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(default='Other', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcecategory')),
                ('link_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcelinktype')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dikcjjfpo/image/upload/v1692718355/default-profile-pic_nwq7pg.png', max_length=255, null=True, verbose_name='Profile Image')),
                ('profile_image_change', models.CharField(blank=True, default='', max_length=1000)),
                ('display_email', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_number', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('facebook', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('teaching_category', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('nothing', 'nothing')], default='nothing', max_length=50)),
                ('classes', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('nothing', 'nothing')], default='nothing', max_length=50)),
                ('is_member', models.BooleanField(default='False')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
