# Generated by Django 3.2 on 2023-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resource',
            field=models.ManyToManyField(to='main_app.Resource'),
        ),
    ]
