# Generated by Django 3.2 on 2023-07-18 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230718_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='unique_event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='short_uuid',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
