# Generated by Django 3.2 on 2023-08-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_resource_event_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(default='None', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.resourcecategory')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcesubcategory'),
        ),
    ]
