# Generated by Django 3.2 on 2023-08-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20230828_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='link_uuid',
        ),
    ]
