# Generated by Django 3.2 on 2023-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20230718_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_uuid',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
