# Generated by Django 3.2 on 2023-07-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_user_short_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='short_uuid',
            new_name='event_short_uuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='short_uuid',
            new_name='member_short_uuid',
        ),
    ]
