# Generated by Django 3.2 on 2023-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_resource_link_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
