# Generated by Django 3.2 on 2023-08-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='embed_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
