# Generated by Django 3.2 on 2023-07-18 14:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20230718_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='display_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Image'),
        ),
    ]
