# Generated by Django 3.2 on 2023-09-01 12:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_resource_embed_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Image')),
                ('aspect_ratio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.aspectratio')),
            ],
        ),
    ]
