# Generated by Django 3.2 on 2023-07-19 12:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dzwyiggcp/image/upload/v1689692743/MREEA/default-profile-pic_yp9kzz.png', max_length=255, null=True, verbose_name='Profile Image'),
        ),
    ]
