# Generated by Django 3.2 on 2023-09-01 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_aspectratio_imageselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageselect',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
