# Generated by Django 3.2 on 2023-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_memberprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='short_bio',
            field=models.CharField(blank=True, default='', max_length=71),
        ),
    ]
