# Generated by Django 3.2 on 2023-09-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_imageselect_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageselect',
            name='aspect_ratio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.aspectratio'),
        ),
    ]
