# Generated by Django 3.2 on 2023-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_memberprofile_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='short_bio',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
