# Generated by Django 3.2 on 2023-07-25 12:24

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_memberprofile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
