# Generated by Django 3.2 on 2023-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_memberprofile_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
