# Generated by Django 3.2 on 2023-08-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_profile_image_url_memberprofile_profile_image_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='office_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='memberprofile',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='company_organization',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='display_address',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='office_number',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
