# Generated by Django 3.2 on 2023-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20230821_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='short_bio',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
