# Generated by Django 3.2 on 2023-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_memberprofile_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='short_bio',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
