# Generated by Django 3.2 on 2023-08-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_memberprofile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='classes',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('nothing', 'nothing')], default='noting', max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='teaching_category',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('nothing', 'nothing')], default='noting', max_length=50),
        ),
    ]
