# Generated by Django 3.2 on 2023-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20230821_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='classes',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('nothing', 'nothing')], default='nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='teaching_category',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('nothing', 'nothing')], default='nothing', max_length=50),
        ),
    ]
