# Generated by Django 3.2 on 2023-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20230821_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='short_bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
