# Generated by Django 3.2 on 2023-08-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20230822_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_image_change',
        ),
    ]
