# Generated by Django 3.2 on 2023-08-23 13:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_event_event_image_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dikcjjfpo/image/upload/v1692796802/mreea-meeting-2_oeygy7.png', max_length=255, null=True, verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dikcjjfpo/image/upload/v1692718355/default-profile-pic_nwq7pg.png', max_length=255, null=True, verbose_name='Profile Image'),
        ),
    ]
