# Generated by Django 3.2 on 2023-08-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.resourcetype'),
        ),
    ]
