# Generated by Django 3.2 on 2023-08-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20230825_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Other', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(default='Other', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='type',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcecategory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcelinktype'),
        ),
    ]
