# Generated by Django 3.2 on 2023-08-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20230825_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category_input',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_type_input',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
