# Generated by Django 3.2 on 2023-08-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20230825_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category_input',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='link_type_input',
        ),
    ]
