# Generated by Django 3.2 on 2023-08-25 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20230825_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.resourcelinktype'),
        ),
    ]
