# Generated by Django 3.2 on 2023-08-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20230825_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_uuid',
        ),
    ]
