# Generated by Django 5.0.2 on 2024-03-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0005_alter_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.folder')),
            ],
        ),
    ]
