# Generated by Django 5.0.6 on 2024-06-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_annoucement_date'),
        ('resources', '0010_folder_created_at_resource_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.folder')),
            ],
        ),
        migrations.DeleteModel(
            name='Annoucement',
        ),
    ]
