# Generated by Django 5.0.6 on 2024-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_delete_annoucement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_made_public',
            field=models.DateTimeField(auto_now_add=True, default='2024-6-4'),
            preserve_default=False,
        ),
    ]
