# Generated by Django 5.0.6 on 2024-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_date_made_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_made_public',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
