# Generated by Django 5.0.6 on 2024-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcement_date_made_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
