# Generated by Django 5.0.2 on 2024-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_cleared_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='important_status',
        ),
    ]
