# Generated by Django 5.0.2 on 2024-05-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_important_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_status',
        ),
    ]
