# Generated by Django 5.0.2 on 2024-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_read_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('friendly_name', models.CharField(max_length=254)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
