# Generated by Django 5.0.2 on 2024-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationCategory',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
