# Generated by Django 5.0.2 on 2024-02-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_folder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='quick_resources',
            field=models.BooleanField(default=False),
        ),
    ]
