# Generated by Django 5.0.2 on 2024-02-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_folder_quick_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
