# Generated by Django 5.0.2 on 2024-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='quick_resources',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='link',
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
