# Generated by Django 5.0.2 on 2024-05-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resourcetype_resource_resource_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceType',
            new_name='Icon',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='icon',
        ),
    ]
