# Generated by Django 5.0.2 on 2024-05-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_rename_resourcetype_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.icon'),
        ),
    ]
